---
title: 协程挂起
tag: Kotlin
category: 协程
---



## Delay

* 线程: `Thread.sleep()`

  `sleep` 让线程进入休眠状态,直到指定的时间之后某种信号或者达到某个条件,线程就会尝试恢复执行

* 协程: `delay` <!-- more -->

  `delay` 会让协程挂起,这个过程并不会阻塞 CPU,甚至可以说从硬件使用效率上讲是"什么都不耽误", 从这个意义上讲 `delay` 也可以要让协程休眠的一种手段

  ```kotlin
  public suspend fun delay(timeMillis: Long) {
      if(timeMillis <= 0) return
      return suspendCancellableCoroutine sc@ {cont: CancellableContinuation<Unit> -> 
      	cont.context.delay.scheduleResumeAfterDelay(timeMillis, cont)
  	}
  }
  ```

   `cont.context.delay.scheduleResumeAfterDelay` 这个操作,可以类比 Android 的 `handler.postDealy` ,本质上就是设置了一个延时回调,时间一到就调用 `resume` 方法让协程继续执行

  

  



## SuspendCancellableCoroutine

```kotlin
    public final override suspend fun join() {
        if (!joinInternal()) { // fast-path no wait
            coroutineContext.checkCompletion()
            return // do not suspend
        }
        return joinSuspend() // slow-path wait
    }

    private suspend fun joinSuspend() = suspendCancellableCoroutine<Unit> { cont ->
        // We have to invoke join() handler only on cancellation, on completion we will be resumed regularly without handlers
        cont.disposeOnCancellation(invokeOnCompletion(handler = ResumeOnCompletion(this, cont).asHandler))
    }
```

`Job.join()` 这个方法会先检查调用者 `Job` 的状态是否已经完成，如果试，就直接返回并继续执行后面的代码而不再挂起，否则就走 `joinSuspend` 。这里只注册了一个完成时的回调



```kotlin
public suspend inline fun <T> suspendCancellableCoroutine(crossinline block: (CancellableContinuation<T>)-> Unit):T = suspendCoroutineUninterceptedOrReturn{ uCont->
    val cancelable = CancellableContinuationImpl(uCont.intercepted(), resumeMode = MODE_CANCELLABLE)
    block(cancellable)
    cancellable.getResult()
}
```

`suspendCoroutineUninterceptedOrReturn` 这个方法帮助我们拿到 `Continuation` 实例，`suspendCoroutineUninterceptedOrReturn` 的返回值类型是 T, 而传入的 lambda  的返回值类型是 Any?,也就是 `cancellable.getResult()` 的类型。

```kotlin
internal fun getResult() :Any? {
    if(trySuspend()) return COROUTINE_SUSPEND // 触发挂起逻辑
    
    if(state is CompletedExceptionally) // 异常立即抛出
    	throw recoverStackTrce(state.cause, this)
    return getSuccessfulResult(state) // 正常结果立即返回
}
```

`trySuspend()` 就是挂起逻辑，表示这个时候目标协程还没有执行完，需要等待结果。

然后判断条件是协程已经执行完，可以直接拿到异常和正常结果的两种情况。

```kotlin
public vla COROUTINE_SUSPEND: Any get() = CoroutineSingletons.COROUTINE_SUSPEND

internal enum class CoroutineSingletons {CONTINE_SUSPEND, UNDECIDED, RESUMED}
```

而 `trySuspend()` 返回的就是一个单例，任何时间协程见到它，就直到自己该挂起了。

## 深入挂起操作

真正的挂起是什么？

```kotlin
suspend fun hello() = suspendCoroutineUninterceptedOrReturn<Int> {
    continuation ->
    log(1)
    thread {
        Thread.sleep(1000)
        log(2)
        continuation.resume(1024)
    }
    log(3)
    CONTROUTINE_SUSPEND
}
```

上面这一个 `suspend` 函数，在 `suspendCoroutineUninterceptedOrReturn` 当中直接返回这个 `COROUTINE_SUSPEND`

## 协程的状态转移

```java
public class ContinuationImpl implements Continuation<Object> {
    private int label = 0;
    private final Continuation<Unit> completion;
    
    public ContinuationImpl(Continuation<Unit> completion) {
        this.completion = completion;
    }
    
    @Override
    public CoroutineContext getContext() {
        return EmptyCoroutineContext.INSTANCE;
    }
    
    @Override
    public void resumeWith(@NotNull Object o) {
        try {
            Object resume = o;
            switch(label) {
                case 0: 
                    LogKt.log(1)
                    result = SuspendFunctionsKt.returnSuspended(this);
                    label++;
                    if(isSuspended(result)) return;
			   case 1:
                    LogKt.log(result);
                    LogKt.log(2)
                    result = DelayKt.delay(1000, this);
                    label++;
                    if(isSuspended(result)) return;
                case 2:
                    LogKt.log(3)
                        result = SuspendedFunctionsKt.returnImmediately(this);
                    label++;
                    if(isSuspended(result)) return;
                case 3:
                    LogKt.log(result);
                    LogKt.log(4)
            }
        }
        completion.resumeWith(Unit.INSTACNE);
    } catch (Exception e){
        completion.resumeWith(e)
    }
}

private boolean isSuspended(Object result) {
    return result == IntrinsicsKt.getCOROUTINE_SUSPENDED();
}
```

> 实际上，在 Kotlin 的标准库中，有一个 `ContinuationImpl` 的累，只不过，它的 `resumeWith` 最终调用到了 `invokeSuspend` 而这个 `invokeSuspend` 实际上就是我们的协程体，通常也就是要给 Lamdba 表达式，我们通过 `launch` 启动协程，传入的 Lambda 表达式，实际上会被编译成一个 `SuspendLambda`  的子类，而它又是 `ContinuationImpl` 的子类。

仿照 `runSuspend` 类，我们实现一个 completion 

```java
public class RunSuspend implements Continuation<Unit> {
    private Object result;
    
    @Override
    public CoroutineContext getContext(){
        return EmptyCoroutineContext.INSTANCE;
    }
    
    @Override
    public void resumeWith(@NotNull Object result) {
        synchronized(this) {
            this.result = result;
            notifyAll();// 协程已结束，通知下面的 wait() 方法停止阻塞
        }
    }
    
    public void await() throws Throwable {
        synchronized(this) {
            while(true) {
                Object result = this.result;
                if(result == null) wait();// 调用了 Object。wait() ，阻塞当前线程，在 notify 或者 notifyAll 调用时返回
                else if(result instanceof Throwable) {
                    throw (Throwable) result;
                } else return;
            }
        }
    }
}
```

```java
public static void main(String...args) throws Throwable {
    RunSuspend runSuspend = new RunSuspend();
    ContinationImpl table = new ContinuationImpl(runSuspend);
    table.resumeWith(Unit.INSTANCE);
    runSuspend.await();
}
```

> 这种写法，简直就是 `suspend main` 的真是面目。

`completion` 传入的 `runSuspend` 实例的 `resumeWith` 实际上是在 `ContinuationImpl` 的 `resumeWith` 的最后才被调用，因为它的 `await()` 一旦进入阻塞状态，直到 `ContinuationImpl` 的整体状态流转完毕才会停止阻塞，此时进程也就运行完毕，可以退出了。